sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ad20041102
  alioss:
    access-key-id: LTAI5t9s8L45q5sEFKJA5seE
    access-key-secret:
    bucket-name: javaweb-chenbolin
    endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    host: 192.168.72.135
    port: 6379
    password:
    database: 2
  wechat:
    appid: wx7fce171dd6af4541
    secret: